import i18n from "i18next";
import { initReactI18next } from "react-i18next";

i18n.use(initReactI18next).init({
  resources: {
    en: {
      // navbar
      translation: {
        nav_menu_1: "Review",
        nav_menu_2: "Analysis",
        nav_menu_3: "Investments",
        nav_menu_4: "Rates",
        nav_menu_5: "Transactions",
        nav_menu_6: "Settings",
        nav_menu_7: "Profile",
        nav_menu_8: "Security",
        nav_menu_9: "API connection",
        nav_menu_10: "Explore",
        nav_menu_11: "Knowledge base",
        nav_menu_12: "Privacy Policy",
        nav_menu_13: "Client Agreement",
        nav_menu_14: "Referral program",
        nav_menu_15: "Logout",
        // reviews
        rev_1: "Review",
        rev_2: "Balance",
        rev_3: "Main account",
        rev_4: "PnL for today",
        rev_5: "Order history",
        rev_6: "A list of the last 10 orders is displayed here",
        rev_7: "No order history",
        tariff_title: "Tariff Plan",
        trial_period: "7 days",
        paid_period: "30 days",
        remaining_days: "days left",
        add_30_days: "Add + 30 days",
        trial_period_title: "Trial Period",
        free_trial: "7 days for free",
        activate_trial:
          "Activate the trial period today and get access to a wide range of features.",
        activate: "Activate",
        trade_open_time: "Trade Open Time",
        trade_close_time: "Trade Close Time",
        buy_price: "Buy Price",
        sell_price: "Sell Price",
        position_volume: "Position Volume",
        profit_or_loss: "Profit or Loss",
        faq_title: "Frequently Asked Questions",
        faq_description:
          "In our knowledge base, you can find answers to the most frequently asked questions.",
        faq_question_1: "How does &Volume decide where to invest funds?",
        faq_question_2: "What is the minimum amount?",
        faq_question_3: "Can I use borrowed money?",
        faq_question_4: "What are the fees and terms of use?",
        faq_question_5: "What security guarantees are there?",
        knowledge_base_link: "Go to Knowledge Base",
        // analysis
        balance_title: "Balance",
        main_account: "Main Account",
        pnl_title: "PnL",
        pnl_today: "PnL for today",
        pnl_period_title: "PnL for Period",
        pnl_period: "PnL from",
        pnl_main_title: "PnL",
        pnl_by_days_title: "PnL by Days",
        executed_orders_title: "Executed Orders",
        executed_orders_description: "Here is the list of open orders.",
        long_order: "Long",
        short_order: "Short",
        no_open_orders: "No open orders",
        no_order_history: "No order history",
        investment_title: "Select method",
        investments_page_title: {
          main_title: "Choose Your Method",
          sub_title:
            "Choose your investment method and feel confident on any time frame.",
        },
        conservative: "Conservative",
        minimumInvestmentAmount: "Minimum Investment Amount",
        riskLevel: "Risk Level",
        projectedYield: "Projected Yield for the Period",
        low: "Low",
        upTo: "up to",
        profitabilityDisclaimer:
          "Profitability is calculated based on historical data and is not a guarantee of future returns",
        select: "Select",
        moderate: "Moderate",
        loremIpsum: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
        medium: "Medium",
        projectedYieldPeriod: "Projected yield for the period",
        "1 год": "1 year",
        "2 года": "2 years",
        "3 года": "3 years",
      },
    },
    ru: {
      translation: {
        // navbar
        nav_menu_1: "Обзор",
        nav_menu_2: "Анализ",
        nav_menu_3: "Инвестиции",
        nav_menu_4: "Тарифы",
        nav_menu_5: "Транзакции",
        nav_menu_6: "Настройки",
        nav_menu_7: "Профиль",
        nav_menu_8: "Безопасность",
        nav_menu_9: "Подключение API",
        nav_menu_10: "Изучить",
        nav_menu_11: "База знаний",
        nav_menu_12: "Политика конфиденциальности",
        nav_menu_13: "Клиентское соглашение",
        nav_menu_14: "Реферальная программа",
        nav_menu_15: "Выйти",
        // reviews
        rev_1: "Обзор",
        rev_2: "Баланс",
        rev_3: "Основной аккаунт",
        rev_4: "PnL за сегодня",
        rev_5: "История ордеров",
        rev_6: "Здесь отображается список последних 10 ордеров",
        rev_7: "Нет истории ордеров",
        tariff_title: "Тарифный план",

        trial_period: "7 дней",
        paid_period: "30 дней",
        remaining_days: "дней осталось",
        add_30_days: "Добавить + 30 дней",
        trial_period_title: "Пробный период",
        free_trial: "7 дней бесплатно",
        activate_trial:
          "Активируйте тестовый период уже сегодня и получите доступ к широкому спектру возможностей.",
        activate: "Активировать",
        trade_open_time: "Время открытия сделки",
        trade_close_time: "Время закрытия сделки",
        buy_price: "Цена покупки",
        sell_price: "Цена продажи",
        position_volume: "Объем позиции",
        profit_or_loss: "Прибыль или убыток",
        faq_title: "Часто задаваемые вопросы",
        faq_description:
          "В нашей базе знаний вы можете найти ответы на самые часто задаваемые вопросы.",
        faq_question_1: "Как &Volume решает, куда инвестировать средства?",
        faq_question_2: "Какая минимальная сумма?",
        faq_question_3: "Могу ли я использовать заёмные деньги?",
        faq_question_4: "Какие комиссии и условия использования?",
        faq_question_5: "Какие гарантии безопасности есть?",
        knowledge_base_link: "Перейти в базу знаний",
        // analysis
        balance_title: "Баланс",
        main_account: "Основной аккаунт",
        pnl_title: "PnL",
        pnl_today: "PnL за сегодня",
        pnl_period_title: "PnL за период",
        pnl_period: "PnL с",
        pnl_main_title: "PnL",
        pnl_by_days_title: "PnL по дням",
        executed_orders_title: "Исполняемые ордера",
        executed_orders_description:
          "Здесь отображается список открытых ордеров.",
        long_order: "Long",
        short_order: "Short",
        no_open_orders: "Нет открытых ордеров",
        no_order_history: "Нет истории ордеров",
        investment_title: "Выберите метод",
        investments_page_title: {
          main_title: "Выберите метод",
          sub_title:
            "Выберите свой метод инвестирования и чувствуйте себя уверенно на любом временном промежутке.",
        },
        conservative: "Консервативный",
        minimumInvestmentAmount: "Минимальная сумма инвестиции",
        riskLevel: "Уровень риска",
        projectedYield: "Прогнозируемая доходность за период",
        low: "Низкий",
        upTo: "до",
        profitabilityDisclaimer:
          "Доходность рассчитана на основе исторических данных и не является гарантией будущей доходности",
        select: "Выбрать",
        moderate: "Умеренный",
        loremIpsum: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",

        medium: "Средний",
        projectedYieldPeriod: "Прогнозируемая доходность за период",

        "1 год": "1 год",
        "2 года": "2 года",
        "3 года": "3 года",
      },
    },
  },
  lng: "en",
  fallbackLng: "en",
  interpolation: {
    escapeValue: false,
  },
});

export default i18n;
