import i18n from "i18next";
import { initReactI18next } from "react-i18next";

i18n.use(initReactI18next).init({
  resources: {
    en: {
      // navbar
      translation: {
        nav_menu_1: "Review",
        nav_menu_2: "Analysis",
        nav_menu_3: "Investments",
        nav_menu_4: "Rates",
        nav_menu_5: "Transactions",
        nav_menu_6: "Settings",
        nav_menu_7: "Profile",
        nav_menu_8: "Security",
        nav_menu_9: "API connection",
        nav_menu_10: "Explore",
        nav_menu_11: "Knowledge base",
        nav_menu_12: "Privacy Policy",
        nav_menu_13: "Client Agreement",
        nav_menu_14: "Referral program",
        nav_menu_15: "Logout",
        // reviews
        rev_1: "Review",
        rev_2: "Balance",
        rev_3: "Main account",
        rev_4: "PnL for today",
        rev_5: "Order history",
        rev_6: "A list of the last 10 orders is displayed here",
        rev_7: "No order history",
        tariff_title: "Tariff Plan",
        trial_period: "7 days",
        paid_period: "30 days",
        remaining_days: "days left",
        add_30_days: "Add + 30 days",
        trial_period_title: "Trial Period",
        free_trial: "7 days for free",
        activate_trial:
          "Activate the trial period today and get access to a wide range of features.",
        activate: "Activate",
        trade_open_time: "Trade Open Time",
        trade_close_time: "Trade Close Time",
        buy_price: "Buy Price",
        sell_price: "Sell Price",
        position_volume: "Position Volume",
        profit_or_loss: "Profit or Loss",
        faq_title: "Frequently Asked Questions",
        faq_description:
          "In our knowledge base, you can find answers to the most frequently asked questions.",
        faq_question_1: "How does &Volume decide where to invest funds?",
        faq_question_2: "What is the minimum amount?",
        faq_question_3: "Can I use borrowed money?",
        faq_question_4: "What are the fees and terms of use?",
        faq_question_5: "What security guarantees are there?",
        knowledge_base_link: "Go to Knowledge Base",
        // analysis
        balance_title: "Balance",
        main_account: "Main Account",
        pnl_title: "PnL",
        pnl_today: "PnL for today",
        pnl_period_title: "PnL for Period",
        pnl_period: "PnL from",
        pnl_main_title: "PnL",
        pnl_by_days_title: "PnL by Days",
        executed_orders_title: "Executed Orders",
        executed_orders_description: "Here is the list of open orders.",
        long_order: "Long",
        short_order: "Short",
        no_open_orders: "No open orders",
        no_order_history: "No order history",
        investment_title: "Select method",
        investments_page_title: {
          main_title: "Choose Your Method",
          sub_title:
            "Choose your investment method and feel confident on any time frame.",
        },
        conservative: "Conservative",
        minimumInvestmentAmount: "Minimum Investment Amount",
        riskLevel: "Risk Level",
        projectedYield: "Projected Yield for the Period",
        low: "Low",
        upTo: "up to",
        profitabilityDisclaimer:
          "* Profitability is calculated based on historical data and is not a guarantee of future returns",
        select: "Select",
        moderate: "Moderate",
        loremIpsum: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
        medium: "Medium",
        projectedYieldPeriod: "Projected yield for the period",
        aggressive: "Aggressive",
        high: "High",
        investments: "Investments",
        activeInvestmentsDescription: "Active investments are displayed here",

        creationTime: "Creation Time",
        investmentMethod: "Investment Method",

        initialAmount: "Initial Amount",
        usedAmount: "Used Amount",
        profitOrLoss: "Profit or Loss",
        delete: "Delete",
        noActiveInvestments: "No active investments",
        faqTitle: "Frequently Asked Questions",
        conservativeTitle: "Conservative",

        maxDrawdown: "Max Drawdown",
        pnl30Days: "PnL(%) for 30 days",
        investment: "Investment",
        min100: "Min. 100",
        available: "Available",
        totalStopLoss: "Total Stop Loss",
        enterMaxAcceptableLoss: "Enter Max Acceptable Loss",
        ifNetLossReaches: "If net loss reaches",
        investmentsWillStop: "investments will stop",
        additionalInformation: "Additional Information",
        volumeStopLoss:
          "&Volume stop-loss is a manual loss limiting mechanism.",
        volumeStopLossDescription:
          "You specify the total absolute loss level in USDT, not a percentage. For example, trading amount is $1000, you set a total stop loss of $200.",
        volumeStopLossExample:
          "In case any of the cryptocurrency in the trade abnormally falls (or rises) in price, your loss will not exceed $200, and the service will temporarily stop opening trades until the market conditions normalize.",
        volumeStopLossDefault:
          "If not set manually, the default total stop loss will be 50% of the exchange deposit.",
        iHaveReadAndAccept: "I have read and accept",
        termsOfUse: "Terms of Use",
        moderateTitle: "Moderate",

        // transactions

        transactions: "Transactions",
        transactionListDescription: "This is a list of transactions",
        processing: "Processing",
        error: "Error",
        completed: "Completed",
        createdAt: "Created at",
        transactionType: "Transaction Type",
        commission: "Commission",
        transactionAmount: "Transaction Amount",
        noTransactions: "No transactions",
        rates: "Rates",
        selectPlan: "Select a Plan",
        paymentDisclaimer:
          "When paying for the tariff, the payment service charges a commission for the transaction. Please specify the amount taking into account the commission.",
        tariffPlanTitle: "Tariff Plan",
        trialPlanDuration: "7 days",
        paidPlanDuration: "30 days",
        remainingDays: "days",
        addDaysLink: "Add + 30 days",
        trialPeriodTitle: "Trial Period",
        freePlanDuration: "7 days free",
        activateTrialPeriod:
          "Activate the trial period today and get access to a wide range of features.",
        activateLink: "Activate",
        startPlanTitle: "Starter",
        startPlanDescription: "For new investors",
        startPlanPrice: "$ 25",
        startPlanPricePerMonth: "/ per month",
        startPlanTradingLimit: "Trading limit up to $400",
        buyButton: "Buy",
        advancedPlanTitle: "Advanced",
        advancedPlanDescription: "For experienced investors",
        advancedPlanPrice: "$ 50",
        advancedPlanPricePerMonth: "/ per month",
        advancedPlanTradingLimit: "Trading limit from $401 to $900",
        professionalPlanTitle: "Professional",
        professionalPlanDescription: "For professionals",
        professionalPlanPrice: "$ 100",
        professionalPlanPricePerMonth: "/ per month",
        professionalPlanTradingLimit: "Trading limit from $901 to $3,000",
        controlTitle: "Maintain Self-Control",
        controlDescription:
          "Investing in cryptocurrency trading is riskier than traditional instruments (bank deposits, long-term stock purchases, etc.). Calculate your risks and don't invest all your savings.",
        profile: "Profile",
        security: "Security",
        apiKeys: "API Keys",
      },
    },
    ru: {
      translation: {
        // navbar
        nav_menu_1: "Обзор",
        nav_menu_2: "Анализ",
        nav_menu_3: "Инвестиции",
        nav_menu_4: "Тарифы",
        nav_menu_5: "Транзакции",
        nav_menu_6: "Настройки",
        nav_menu_7: "Профиль",
        nav_menu_8: "Безопасность",
        nav_menu_9: "Подключение API",
        nav_menu_10: "Изучить",
        nav_menu_11: "База знаний",
        nav_menu_12: "Политика конфиденциальности",
        nav_menu_13: "Клиентское соглашение",
        nav_menu_14: "Реферальная программа",
        nav_menu_15: "Выйти",
        // reviews
        rev_1: "Обзор",
        rev_2: "Баланс",
        rev_3: "Основной аккаунт",
        rev_4: "PnL за сегодня",
        rev_5: "История ордеров",
        rev_6: "Здесь отображается список последних 10 ордеров",
        rev_7: "Нет истории ордеров",
        tariff_title: "Тарифный план",

        trial_period: "7 дней",
        paid_period: "30 дней",
        remaining_days: "дней осталось",
        add_30_days: "Добавить + 30 дней",
        trial_period_title: "Пробный период",
        free_trial: "7 дней бесплатно",
        activate_trial:
          "Активируйте тестовый период уже сегодня и получите доступ к широкому спектру возможностей.",
        activate: "Активировать",
        trade_open_time: "Время открытия сделки",
        trade_close_time: "Время закрытия сделки",
        buy_price: "Цена покупки",
        sell_price: "Цена продажи",
        position_volume: "Объем позиции",
        profit_or_loss: "Прибыль или убыток",
        faq_title: "Часто задаваемые вопросы",
        faq_description:
          "В нашей базе знаний вы можете найти ответы на самые часто задаваемые вопросы.",
        faq_question_1: "Как &Volume решает, куда инвестировать средства?",
        faq_question_2: "Какая минимальная сумма?",
        faq_question_3: "Могу ли я использовать заёмные деньги?",
        faq_question_4: "Какие комиссии и условия использования?",
        faq_question_5: "Какие гарантии безопасности есть?",
        knowledge_base_link: "Перейти в базу знаний",
        // analysis
        balance_title: "Баланс",
        main_account: "Основной аккаунт",
        pnl_title: "PnL",
        pnl_today: "PnL за сегодня",
        pnl_period_title: "PnL за период",
        pnl_period: "PnL с",
        pnl_main_title: "PnL",
        pnl_by_days_title: "PnL по дням",
        executed_orders_title: "Исполняемые ордера",
        executed_orders_description:
          "Здесь отображается список открытых ордеров.",
        long_order: "Long",
        short_order: "Short",
        no_open_orders: "Нет открытых ордеров",
        no_order_history: "Нет истории ордеров",
        investment_title: "Выберите метод",
        investments_page_title: {
          main_title: "Выберите метод",
          sub_title:
            "Выберите свой метод инвестирования и чувствуйте себя уверенно на любом временном промежутке.",
        },
        conservative: "Консервативный",
        minimumInvestmentAmount: "Минимальная сумма инвестиции",
        riskLevel: "Уровень риска",
        projectedYield: "Прогнозируемая доходность за период",
        low: "Низкий",
        upTo: "до",
        profitabilityDisclaimer:
          "* Доходность рассчитана на основе исторических данных и не является гарантией будущей доходности",
        select: "Выбрать",
        moderate: "Умеренный",
        loremIpsum: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
        aggressive: "Агрессивный",
        medium: "Средний",
        projectedYieldPeriod: "Прогнозируемая доходность за период",
        high: "Высокий",
        investments: "Инвестиции",
        activeInvestmentsDescription: "Здесь отображаются активные инвестиции",
        creationTime: "Время создания",
        investmentMethod: "Метод инвестирования",

        initialAmount: "Начальная сумма",
        usedAmount: "Используемая сумма",
        profitOrLoss: "Прибыль или убыток",
        delete: "Удалить",
        noActiveInvestments: "Нет активных инвестиций",
        faqTitle: "Часто задаваемые вопросы",
        conservativeTitle: "Консервативный",

        maxDrawdown: "Макс. просадка",
        pnl30Days: "Pnl(%) за 30 дней",
        investment: "Инвестиции",
        min100: "Мин. 100",
        available: "Доступно",
        totalStopLoss: "Общий стоп-лосс",
        enterMaxAcceptableLoss: "Введите максимально приемлемый убыток",
        ifNetLossReaches: "Если чистый убыток достигнет",
        investmentsWillStop: "инвестиции прекратятся",
        additionalInformation: "Дополнительная информация",
        volumeStopLoss:
          "В &Volume стоп-лосс это ручной механизм ограничения потерь.",
        volumeStopLossDescription:
          "Вы указываете общий абсолютный уровень потерь в USDT, а не процентный. Например, сумма торгов $1000, вы устанавливаете общий стоп-лосс $200.",
        volumeStopLossExample:
          "В случае, если в какой-либо из сделок криптовалюта аномально снизится (или возрастет) в цене, ваш убыток не превысит $200, а сервис временно перестанет открывать сделки до нормализации рыночных условий.",
        volumeStopLossDefault:
          "Если не установить значение вручную, то по умолчанию общий стоп-лосс составит 50% от депозита на бирже.",
        iHaveReadAndAccept: "Я прочитал(-а) и принимаю",
        termsOfUse: "Условия использования",
        moderateTitle: "Умеренный",
        transactions: "Транзакции",
        transactionListDescription: "Здесь отображается список транзакций",
        processing: "В обработке",
        error: "Ошибка",
        completed: "Выполнена",
        createdAt: "Время создания",
        transactionType: "Тип транзакции",
        commission: "Комиссия",
        transactionAmount: "Сумма транзакции",
        noTransactions: "Нет транзакций",
        rates: "Тарифы",
        selectPlan: "Выберите план",
        paymentDisclaimer:
          "При оплате тарифа платёжный сервис берет комиссию за проведение транзакции. Внимательно указывайте сумму с учётом комиссии.",
        tariffPlanTitle: "Тарифный план",
        trialPlanDuration: "7 дней",
        paidPlanDuration: "30 дней",
        remainingDays: "дней",
        addDaysLink: "Добавить + 30 дней",
        trialPeriodTitle: "Пробный период",
        freePlanDuration: "7 дней бесплатно",
        activateTrialPeriod:
          "Активируйте тестовый период уже сегодня и получите доступ к широкому спектру возможностей.",
        activateLink: "Активировать",
        startPlanTitle: "Стартовый",
        startPlanDescription: "Для новых инвесторов",
        startPlanPrice: "$ 25",
        startPlanPricePerMonth: "/ ежемесячно",
        startPlanTradingLimit: "Лимит суммы в торгах до $400",
        buyButton: "Купить",
        advancedPlanTitle: "Улучшенный",
        advancedPlanDescription: "Для опытных инвесторов",
        advancedPlanPrice: "$ 50",
        advancedPlanPricePerMonth: "/ ежемесячно",
        advancedPlanTradingLimit: "Лимит суммы в торгах до $401 до $900",
        professionalPlanTitle: "Продвинутый",
        professionalPlanDescription: "Для профессионалов",
        professionalPlanPrice: "$ 100",
        professionalPlanPricePerMonth: "/ ежемесячно",
        professionalPlanTradingLimit: "Лимит суммы в торгах до $901 до $3 000",
        controlTitle: "Не теряйте самоконтроль",
        controlDescription:
          "Инвестиции в торговлю криптовалютой рискованнее, чем традиционные инструменты (вклад в банк, покупка акцией на долгий срок и т.п.), рассчитывайте свои риски и не инвестируйте все свои сбережения.",
        profile: "Профиль",
        security: "Безопасность",
        apiKeys: "Ключи API",
      },
    },
  },
  lng: "en",
  fallbackLng: "en",
  interpolation: {
    escapeValue: false,
  },
});

export default i18n;
